### PR TITLE
Reversing wall and sub-surfaces re issue #119

### PR DESCRIPTION
**Pull request by DavidGoldwasser**
re Issue #119

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
Should see a bunch of changes like this where surface and sub-surface vertices were reversed.

screenshot 2016-11-02 11 14 38

**Comment by DavidGoldwasser** [comment]
@asparke2 want me to fix issue #108 with this pull request as well?

**Comment by asparke2** [comment]
@DavidGoldwasser sure that would be good.  Please check the original Prototype and Reference IDFs to make sure it matches them.  If they also appear to have issues, we need to tell PNNL.

**Comment by DavidGoldwasser** [comment]
@asparke2 based on the details in UH post it seems like the Reference model correctly was 47.6m while the prototype model was just 37.5m. Sounds like @jmarrec reached out to PNNL but we can follow up on that. I'll fix the model in openstudio-standards. I'll check all three geometry models for large_office.
https://unmethours.com/question/18033/why-is-large-office-prototype-building-so-short/?answer=18036#post-id-18036

**Pull request merged**
