### PR TITLE
fixing schedule inconsistencies with constant/hourly schedules

### PR DESCRIPTION
**Pull request by mpraprost**
- changed schedule type from constant to hourly for schedules with hourly values
- got rid of extra schedule values in constant schedules
- added missing values in hourly schedules

fyi - some new college model schedules got wrapped into this commit when i rebuilt the jsons

### CODE REVIEW

**Comment by mdahlhausen** [comment]
Fixes #762

**Comment by mdahlhausen** [comment]
@mpraprost this is throwing an error in LargeOffice-90.1-2013.

**Comment by mpraprost** [comment]
@mdahlhausen this looks like a result of me changing the schedule type from constant to hourly, because the schedule had hourly values. any ideas why this would break the test?

**Comment by mdahlhausen** [comment]
@mpraprost I checked the .idf copy of the PNNL prototypes and the openstudio-standards test regression model was incorrect.  I fixed the regression model so this should pass now.

**Pull request merged**
