### PR TITLE
Weather std update

### PR DESCRIPTION
**Pull request by mdahlhausen**
Adds in both ASHRAE 169-2006 and ASHRAE 169-2013 to the spreadsheet and the code base.
 - Includes updated city locations for each climate zone
 - Includes updated ground temperature for each climate zone
 - Updates the prototype models and tests to use ASHRAAE 169-2013.

Alternative solution to accommodate pull #572

### CODE REVIEW

**Comment by wta12** [comment]
@mdahlhausen: May you verify climate zone data hash from: [data](https://github.com/NREL/openstudio-standards/blob/f6c5912a2a45cc2cbc58f7828365741d714a0605/lib/openstudio-standards/standards/ashrae_90_1/data/ashrae_90_1.climate_zones.json) and [code](
https://github.com/NREL/openstudio-standards/blob/f6c5912a2a45cc2cbc58f7828365741d714a0605/lib/openstudio-standards/weather/Weather.Model.rb) 
8A/B and 7A/B use same city ??? 
  ```
 {
      "name": "ASHRAE 169-2013-7A",
      "standard": "ASHRAE 169-2013",
      "representative_city": "International Falls, MN",
      "bcl_weather_component_id": null
    },
    {
      "name": "ASHRAE 169-2013-7B",
      "standard": "ASHRAE 169-2013",
      "representative_city": "International Falls, MN",
      "bcl_weather_component_id": null
    },
    {
      "name": "ASHRAE 169-2013-8A",
      "standard": "ASHRAE 169-2013",
      "representative_city": "Fairbanks, AK",
      "bcl_weather_component_id": null
    },
    {
      "name": "ASHRAE 169-2013-8B",
      "standard": "ASHRAE 169-2013",
      "representative_city": "Fairbanks, AK",
      "bcl_weather_component_id": null
    }
 {
      "name": "ASHRAE 169-2006-7A",
      "standard": "ASHRAE 169-2006",
      "representative_city": "Duluth, MN",
      "bcl_weather_component_id": null
    },
    {
      "name": "ASHRAE 169-2006-7B",
      "standard": "ASHRAE 169-2006",
      "representative_city": "Duluth, MN",
      "bcl_weather_component_id": null
    },
    {
      "name": "ASHRAE 169-2006-8A",
      "standard": "ASHRAE 169-2006",
      "representative_city": "Fairbanks, AK",
      "bcl_weather_component_id": null
    },
    {
      "name": "ASHRAE 169-2006-8B",
      "standard": "ASHRAE 169-2006",
      "representative_city": "Fairbanks, AK",
      "bcl_weather_component_id": null
    }
```
 Hanoi  has climate zone 1A in both 2006 and 2013 version (CDD 50F ~ 5223) 
```
'ASHRAE 169-2006-0A' => 'VNM_Hanoi.488200_IWEC.epw'
'ASHRAE 169-2013-0A' => 'VNM_Hanoi.488200_IWEC.epw'
```

**Comment by mdahlhausen** [comment]
Yes, climate 7/7A/7B are the same city and 8/8A/8B are the same city.  ASHRAE introduced climate zone 0A in 2017, and Hanoi falls into that.

**Comment by lymereJ** [comment]
@wta12, @mdahlhausen , @jiangithub  - The representative cities for climate zone 7 and 8 are correct.

@mdahlhausen - The weather files for CZ 0A and 0B are not the same that we're using, were they added by you? I don't remember doing it when we worked on the location/weather file update.

**Comment by wta12** [comment]
@mdahlhausen : Could you give me a link/document for Hanoi as zone 0A  ?? It's not matching the grading table/map/formula of ASHRAE 169-2013 version which I have.

**Comment by mdahlhausen** [comment]
@lymereJ we climate zone 0A and 0B for the Zero Energy guides work.  Seems like the 0A classification for Hanoi is incorrect in the guides.  What are you using for 0A?

**Comment by jiangithub** [comment]
We use the following two TMY files as representative cities for CZ0A and CZ0B. They are based on recommendations of a Climate Zone Working Group under ASHRAE SSPC 90.1. We cannot provide a reference yet but they might be included in the upcoming 90.1-2019 Determination TSD report (expected publication in June 2020). 

VNM_Ho.Chi.Minh.City-Tan.Son.Nhat.AP.489000_IWEC2.epw
ARE_Dubai.Intl.AP.411940_IWEC2.epw

**Pull request merged**
