### PR TITLE
Use OA-based SAT reset instead of warmest zone

### PR DESCRIPTION
**Pull request by lymereJ**
The proposed changes switch the 90.1 prototypes using VAV systems from using a warmest zone to a OA-based SAT reset.

### CODE REVIEW

**Comment by lymereJ** [comment]
Adding @leijerry888 as a reviewer just for a test.

**Review by leijerry888 — APPROVED** [review]
test approve msg

**Review by leijerry888 — APPROVED** [review]

**Comment by lymereJ** [comment]
@mdahlhausen, can I now update this branch from master?

**Comment by mdahlhausen** [comment]
@lymereJ yes, please update

**Comment by lymereJ** [comment]
All tests are now passing.

**Review by mdahlhausen — APPROVED** [review]

**Pull request merged**
