### PR TITLE
Remove Errant Surface in the Detailed Small Office Prototype

### PR DESCRIPTION
**Pull request by lymereJ**
While reviewing the prototype @CCN18 noticed that Surface 135 which is assigned to the attic has its outside boundary condition set to `Ground`. After further review it seems that this is an errant surface and should be removed. ORNL/NREL should probably confirm before merging the pull request.

### CODE REVIEW

**Comment by mdahlhausen** [comment]
@lymereJ the surface matching needs to be reapplied.

Can you also make these additional changes?:
- Rename the surfaces in the OfficeDetailed models?  There is a sketchup-userscript called _RenameSpaceSurfacesBasedonParentSpaceandOrientation_ on the [UnmetHours github](https://github.com/UnmetHours/sketchup-scripts) as well as a measure on BCL that does this.  That would make it easier to reference surfaces during future debugging/editing of models.
- delete the ASHRAELargeOfficeDetailed and ASHRAELargeOfficeDetailed_1 directories?  They are just an artifact of saving the .osm files in Sketchup.  I accidentally merged those in to master.

**Comment by lymereJ** [comment]
@mdahlhausen, it looks like this isn't the only issue that exist with the attic. Here all the surfaces that are assigned to the attic for the detailed small office prototype ((90.1-2013, CZ8A):

**Boundary Condition - Construction - Surface Type (Surface Name)**
Surface - Typical Interior Floor - Floor (Surface 127)
Outdoors - Typical Wood Joist Attic Floor R-58.82 - Roof (Surface 128)
Outdoors - Typical Wood Joist Attic Floor R-58.82 - Roof (Surface 129)
Outdoors - Typical Wood Joist Attic Floor R-58.82 - Roof (Surface 130)
Outdoors - Typical Wood Joist Attic Floor R-58.82 - Roof (Surface 131)
Surface - Typical Interior Floor - Floor (Surface 132)
Surface - Typical Interior Floor - Floor (Surface 133)
Ground - Typical Insulated Carpeted 8in Slab Floor - Floor (Surface 135)
Outdoors - Typical Insulated Exterior Mass Floor R-26.32 - Floor (Surface 148)
Outdoors - Typical Insulated Exterior Mass Floor R-26.32 - Floor (Surface 149)
Outdoors - Typical Insulated Exterior Mass Floor R-26.32 - Floor (Surface 151)
Surface - Typical Interior Floor - Floor (Surface 158)
Surface - Typical Interior Floor - Floor (Surface 159)
Surface - Typical Interior Floor - Floor (Surface 160)
Surface - Typical Interior Floor - Floor (Surface 161)
Surface - Typical Interior Floor - Floor (Surface 163)
Surface - Typical Interior Floor - Floor (Surface 164)
Surface - Typical Interior Floor - Floor (Surface 165)
Surface - Typical Interior Floor - Floor (Surface 167)
Surface - Typical Interior Floor - Floor (Surface 168)
Surface - Typical Interior Floor - Floor (Surface 169)
Surface - Typical Interior Floor - Floor (Surface 171)
Surface - Typical Interior Floor - Floor (Surface 172)
Surface - Typical Interior Floor - Floor (Surface 173)
Surface - Typical Interior Floor - Floor (Surface 174)
Outdoors - Typical Insulated Exterior Mass Floor R-26.32 - Floor (Surface 8)

As you can see there are way too many surfaces with `Outdoors` as a boundary conditions. Surfaces that are exposed to the outdoors should not be insulated, the surface between the zone and the attic should be insulated. Insulation should be of the same type.

Since more modifications seem to be required perhaps @piljaeim at ORNL should take over.

**Comment by mdahlhausen** [comment]
Thanks for looking into it.  Also, the attic floor in the small office shouldn't be a heavy mass slab.  This was an issue that got fixed in some of the DEER prototype models if someone wants to reference that.

**Comment by lymereJ** [comment]
One more thing, when using OpenStudio-Standards to created a detail small office prototype, a warning shows up: `Space type properties lookup failed: {"template"=>"90.1-2013", "building_type"=>"Office", "space_type"=>"SmallOffice - Attic"}`. This seems to be happening because the `SmallOffice - Attic` space type is not present in the Space Types tab of the Google Spreadsheet. This has probably no impact on the simulations but adding this space type to the spreadsheet might help getting rid of the warning.

**Comment by mdahlhausen** [comment]
@lymereJ any update on this?

**Comment by lymereJ** [comment]
@mdahlhausen - No, we were operating under the assumption that ORNL would take over since it's a prototype they developed.

**Comment by mdahlhausen** [comment]
@piljaeim is this something you'll have time to address in the next few weeks before our next openstudio-standards release?

**Comment by mdahlhausen** [comment]
Issues resolved as part of #753 and #803

**Pull request closed without merging**
