### PR TITLE
Add doors in the geometry osm files for ASHRAE building models

### PR DESCRIPTION
**Pull request by yunyangye**
Add doors in the geometry osm files for ASHRAE building models and the number of doors in the new geometry osm files are the same as the prototype models (idf) created by PNNL. Further, conduct minor changes for the geometries of 90.1-2013 large hotel and 90.1-2013 secondary school, which are the same as the prototype models (idf) now.

### CODE REVIEW

**Comment by asparke2** [comment]
@lymereJ can you take a look at this PR and see if it's ready to go?  It may require @leijerry888 to regenerate the expected regression models.

**Comment by lymereJ** [comment]
@mdahlhausen - I removed the in progress tag, @yunyang-ye confirmed that this PR is ready, please let us know if you have any comments. Either him or I will update the regression models and performance tests results by tomorrow.

**Comment by mdahlhausen** [comment]
@lymereJ I'll review this tomorrow.

**Comment by mdahlhausen** [comment]
@lymereJ looking at the most recent merge test results it seems we need to rebuild the expected results and regression models.  I tried to manually merge the expected results file and it looks like it didn't save make out with enough significant figures.

Also it looks like some restaurant SWH schedules got a name change?

**Comment by lymereJ** [comment]
Huh, strange. We'll commit updated models and results shortly.

**Comment by mdahlhausen** [comment]
@lymereJ I had messed up some changes in the performance results from switching the exterior equipment to electric from gas.  I re-updated from master.  Should be good to re-run the regression model / performance results update now.

Also make sure you are using a linux machine to regenerate the results/models.

**Comment by lymereJ** [comment]
Results/models regenerated (on linux) and pushed. Sorry for the delay.

**Pull request merged**
