### PR TITLE
College new 2021

### PR DESCRIPTION
**Pull request by ybae0330**
Updated college building model

### CODE REVIEW

**Review by mdahlhausen — CHANGES_REQUESTED** [review]
@ybae0330 I updated this from the main branch.  Let me know once you've removed the elevators from the VAV HVAC list and dealt with the sizing error.  I can jump on a call to try to debug that further if you are still stuck.
Marking this as "request changes" for now until those items are addressed.

**Comment by ybae0330** [comment]
> @ybae0330 I updated this from the main branch. Let me know once you've removed the elevators from the VAV HVAC list and dealt with the sizing error. I can jump on a call to try to debug that further if you are still stuck.
> Marking this as "request changes" for now until those items are addressed.

@mdahlhausen I've made couple of changes to resolve the sizing error. It seems the error is now resolved!

**Review by mdahlhausen — CHANGES_REQUESTED** [review]
This pull request needs to address a few more things before merging:

1) The `infiltration_per_zone_entrydoor` variable is initialized, but never applied to the `infiltration_entrydoor` space infiltration object. [Example here](https://github.com/NREL/openstudio-standards/blob/College_new_2021/lib/openstudio-standards/prototypes/common/buildings/Prototype.College.rb#L40).

2) The `add_door_infiltration` method needs to be documented.  See the documentation right before the definition of the `add_door_infiltration` method in other prototypes for an example of how to document the parameters and return values.
3) The code contains several rubocop errors - trailing white spaces, under-indentation, etc.  You can see these with `bundle exec rake rubocop:show`.  Address the rubocop errors for files you've added/edited when making a pull request.  It would also be appropriate to use a guard clause for the DOE Ref templates rather than putting it behind an `unless`.  See the other `add_door_infiltration` for an example of a guard clause applied to this method.

Documentation and rubocop are explained more in the [Developer Information](https://github.com/NREL/openstudio-standards/blob/master/docs/DeveloperInformation.md).

**Comment by mdahlhausen** [comment]
Also:
Add `test_college.rb` to `circleci_tests.txt` and `circleci_tests.json`.

**Comment by mdahlhausen** [comment]
@ybae0330 bumping this again; there are a few more items to address before this can be merged.  See comments above.

**Comment by ybae0330** [comment]
> @ybae0330 bumping this again; there are a few more items to address before this can be merged. See comments above.

@mdahlhausen All other errors including RuboCop error are addressed but still infiltration_per_zone_entrydoor variable does not applied to the infiltration_entrydoor space infiltration object

**Review by mdahlhausen — APPROVED** [review]

**Comment by mdahlhausen** [comment]
Thanks @ybae0330 !

**Comment by mdahlhausen** [comment]
@ybae0330 Now that this is merged, let me know if I can delete the other college branches too.

**Comment by ybae0330** [comment]
Yes, you can delete all other college branches. Thank you!

**Pull request merged**
