### PR TITLE
Update simulation.rb

### PR DESCRIPTION
**Pull request by mdahlhausen**
close the sql file if open in addition to resetting the sql file

### CODE REVIEW

**Comment by weilixu** [comment]
The test_infiltration function failed. I am investigating the error in prm test file

**Comment by weilixu** [comment]
The SQL issue is fixed, 3.2.1 pass CI test @mdahlhausen

**Comment by mdahlhausen** [comment]
@weilixu I'm doing some more checks before I merge this.  I'm worried it could cause some issues in other projects that use standards, similar to the initial failure we saw on the PRM tests on the CI.  I may just remove the changes to `simulation.rb` and keep the changes you made to `test_appendix_g_prm.rb`.  Is that ok?

**Comment by mdahlhausen** [comment]
May reopen this and reapply the changes to `simulation.rb` in the future after more testing.

**Pull request merged**
