### PR TITLE
Regression and Simulation Tests for the DOE/90.1 Prototypes

### PR DESCRIPTION
**Pull request by lymereJ**
The proposed changes add regression and simulation tests for the DOE/901 prototypes. This first commit includes the structure of the tests. The result CSV file used for comparison and the *true* models for the regression test still need to be produced and added to the pull request.

### CODE REVIEW

**Comment by lymereJ** [comment]
@asparke2, @mdahlhausen - the last build for this PR failed because of `test/doe_prototype/test_add_hvac_systems.rb`. I ran this test on my machine using my local branch which is the same as what is in the latest commit and it didn't fail. Am I missing something?

**Comment by mdahlhausen** [comment]
@lymereJ I think there were some HVAC systems that started showing unmet hours with the weather location changes from the ASHRAE 169 merge.  Can you update / pull changes to those tests from master if there are any into this branch?

Otherwise, I'll pull down this branch and debug the HVAC system tests.

**Comment by lymereJ** [comment]
@mdahlhausen I did an update from master on March 7. It looks like you merged #605 on the 6th, so it should be good, shouldn't it?

**Comment by lymereJ** [comment]
@asparke2 - It looks like #663 did the trick!

**Pull request merged**
