### PR TITLE
Refix Issue #503 in json and spreadsheet

### PR DESCRIPTION
**Pull request by leijerry888**
this fix was in PR #579, it should have fixed issue #503  but lost later.

JSON file for 90.1 construction is updated. The following spreadsheet cells are also updated.

https://docs.google.com/spreadsheets/d/1MYQGPd3WFaaSHGnwcmYoNi7TLDgE76LjecTEkY0vGco/edit#gid=1090562793&range=F222:I222
https://docs.google.com/spreadsheets/d/1MYQGPd3WFaaSHGnwcmYoNi7TLDgE76LjecTEkY0vGco/edit#gid=1090562793&range=F228:I228

### CODE REVIEW

**Comment by mdahlhausen** [comment]
@leijerry888 will this impact the regression tests?  If so, could you update those too? Thanks!

**Comment by leijerry888** [comment]
I will update both regression test models and performance test expectations

**Comment by leijerry888** [comment]
performance test expectations for all 1216 records and regression test models for all building types will be updated. osm files of  other bldg types have changes in things such as OS:Rendering:Color and OS:ElectricEquipment:Definition

**Comment by leijerry888** [comment]
ready to merge

**Pull request merged**
