### PR TITLE
Building Energy Standards Envelope Requirements Data Update

### PR DESCRIPTION
**Pull request by leijerry888**
Updates have been made to the Building Energy Standards Data repository, see [here](https://github.com/pnnl/building-energy-standards-data/commit/0546f80831a9b7913524b9fb7b3f242769e308d3). This pull request was automatically generated.

### CODE REVIEW

**Comment by lymereJ** [comment]
@mdahlhausen - This PR is ready for your review. The only diffs are regression/performance related. I spot-checked them and they are expected.

**Review by mdahlhausen — CHANGES_REQUESTED** [review]
Changes:
- [ ] include 'ClimateZone 0' construction properties, at least for ASHRAE 90.1-2016 and 2019, which include it. The construction .json updates are removing the existing data.
- [ ] 90.1-2013 and 90.1-2016 use 'Metal framing (all other)' in window construction properties, but should be split into 'Nonmetal framing, all', 'Metal framing, fixed', 'Metal framing, operable', and 'Metal framing, entrance door'. This relates to #958.
- [ ] I see you cut off the 'Window' name from exterior window construction property names. E.g. "U 1.22 SHGC 0.54 Simple Glazing Window" vs. "U 1.22 SHGC 0.54 Simple Glazing". That may be ok. I added Window a while ago to avoid confusion with the material of the same name, which created some confusion. If you'd prefer to leave 'Window', I can adapt, but it may be nice to include. Thoughts?

**Comment by lymereJ** [comment]
@mdahlhausen - `ClimateZone 0` construction properties are included in this PR.

**Comment by mdahlhausen** [comment]
> @mdahlhausen - `ClimateZone 0` construction properties are included in this PR.

oh my bad. I see they are, included after ClimateZone 8. I may move them to the start of the .json for consistency.

**Comment by lymereJ** [comment]
> * [ ]  90.1-2013 and 90.1-2016 use 'Metal framing (all other)' in window construction properties, but should be split into 'Nonmetal framing, all', 'Metal framing, fixed', 'Metal framing, operable', and 'Metal framing, entrance door'. This relates to [Revise fenestration categories #958](https://github.com/NREL/openstudio-standards/issues/958).

The PR actually do that split, but use slightly different nomenclature. We can change it in the database.

**Comment by lymereJ** [comment]
> * [ ]  I see you cut off the 'Window' name from exterior window construction property names. E.g. "U 1.22 SHGC 0.54 Simple Glazing Window" vs. "U 1.22 SHGC 0.54 Simple Glazing". That may be ok. I added Window a while ago to avoid confusion with the material of the same name. If you'd prefer to leave 'Window', I can adapt, but it may be nice to include. Thoughts?

We can roll that back if you feel strongly about it. Our thought was that it would perhaps avoid having multiple identical constructions. For example: `U 1.22 SHGC 0.54 Simple Glazing Window`, `U 1.22 SHGC 0.54 Simple Glazing Skylight`, and `U 1.22 SHGC 0.54 Simple Glazing Door` would all use a material named `U 1.22 SHGC 0.54 Simple Glazing`.

**Comment by mdahlhausen** [comment]
@lymereJ Thanks for the responses. I moved the climate zone 0 data up to the top of the construction properties .jsons. You may need short line of code to export in that order from the database.

I agree with your approach to simplify constructions. I removed any references to 'Simple Glazing Window' and 'Simple Glazing Skylight' and replaced them with 'Simple Glazing'.

Can you explain the standards construction type in 90.1-2013 and 90.1-2016? I see 'Metal framing (all other)' listed in the .jsons, but that doesn't correspond to types in the standard.

**Comment by lymereJ** [comment]
Thanks! We're making changes to the database and will "re-sync" the data from this PR with it. It should clarify the 90.1-2013/6 terminology differences.

**Comment by lymereJ** [comment]
@mdahlhausen - Looks like the tests are passing!

**Review by mdahlhausen — APPROVED** [review]
Looks good, thanks for the update!

**Pull request merged**
