### PR TITLE
Space Types Assumptions Update

### PR DESCRIPTION
**Pull request by lymereJ**
The 90.1-2004 standalone retail prototype could not be created because of a severe error in the sizing run. No outdoor air was being assigned to the core retail space. The proposed changes add a line in the Space Types tab of the Google Sheet for this space (it was already defined for all the other 90.1 standards except for 90.1-2004). The test didn't catch this because it only creates the 2007 and 2013 version of 90.1 prototypes.

### CODE REVIEW

**Comment by mdahlhausen** [comment]
@lymereJ It appears that the data was there, just that at some point the Building Type for the 90.1-2004 template got changed to LargeOffice in the spreadsheet.  Probably from a careless drag-and-replace.

See the OpenStudio_Standards_space_types.json on master:
```
  "template": "90.1-2004",
  "building_type": "LargeOffice",
  "space_type": "Retail",
```

Can you delete the row you added and switch the building type for the above line back to Retail?

Also, looking at the space types, it looks like these fields aren't aligned with the other 90.1-2004 Retail space types (in Large Hotel):
 - Lighting Standard
 - Lighting Primary Space Type
 - Ventilation Primary Space Type
 - Cooling Setpoint Schedule

Can you filter the spaces types to:
 - **Templates**: 90.1-2004, 90.1-2007, 90.1-2010, 90.1-2013
 - **Space Types**: Retail, Retail2, Core_Retail, Front_Retail
And make sure that the above inputs are aligned as you would like them?  Then rebuild and recommit to the branch.

Thanks!

**Comment by lymereJ** [comment]
@mdahlhausen, will do, thanks for point it out. Using the filter you recommended I spotted other issues (e.g. Retail in Large Hotel has a LPD of 1.7 W/ft2 for 90.1-2004 but in the Commercial Building Prototype it's set to 1.5 W/ft2), I think I need to huddle up with our team before tackling these changes.

**Comment by mdahlhausen** [comment]
@lymereJ we are looking to do a code freeze and openstudio-standards release at the end of this week.  Can you check with the team to get the correct data into the spreadsheet for Retail ASHRAE 90.1-2004?  Thanks!

**Comment by lymereJ** [comment]
@mdahlhausen after you pointed out the inconsistencies for that particular building type and code version, I started looking at others. I notice a lot of other inconsistencies and inputs that needed to be modified in the Space Types tab of the spreadsheet. Unfortunately, all the issues have not yet been addressed. I'll check-in with @jiangithub and get back to you.

**Comment by mdahlhausen** [comment]
space type changes already included in pull #605.
@lymereJ make a new pull request once you've fixed other parameter changes to space types, etc.

**Pull request closed without merging**
