### PR TITLE
Infiltration refactor

### PR DESCRIPTION
**Pull request by mdahlhausen**
Pull request overview
---------------------
This PR is a major update in how openstudio-standards handles infiltration.

Previously, infiltration data was included as a target infiltration rate in the data for each space type with a fixed schedule unique to a prototype. Coefficients were wind driven only.

This PR moves infiltration to a property of building construction - applied universally to the building based on a total building infiltration rate, and with schedules calculated from the predominant building HVAC system schedules. Coefficients use the NIST data for prototypes, which were developed from CONTAM pressure network modeling on the prototypes.

The infiltration values are must more accurate, and give more flexibility in converting measured infiltration rates to design values in the energy model.

A future update may change the NIST correlation coefficients to be determined from building geometry, rather than the closest building type (a proxy for building type).

### Pull Request Author
 - [x] Method changes or additions
 - [x] Data changes or additions
 - [x] Added tests for added methods
 - [x] If methods have been deprecated, update rest of code to use the new methods
 - [x] Documented new methods using [yard syntax](https://rubydoc.info/gems/yard/file/docs/GettingStarted.md)
 - [x] Resolved yard documentation errors for new code (ran `bundle exec rake doc`)
 - [x] Resolved rubocop syntax errors for new code (ran `bundle exec rake rubocop`)
 - [x] All new and existing tests passes

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [x] Perform a code review on GitHub
 - [ ] All related changes have been implemented: method additions, changes, tests
 - [ ] Check rubocop errors
 - [ ] Check yard doc errors
 - [ ] If fixing a defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If a new feature, test the new feature and try creative ways to break it
 - [x] CI status: all green or justified

### CODE REVIEW

**Comment by mdahlhausen** [comment]
@weilixu this is giving one error in CI testing in the appendix g prm tests:
"The proposed air leakage rate of the building envelope (LargeHotel) at a fixed building pressure of 75 Pa (1.51 cfm/ft2) is different than the requirement (0.5 cfm/ft2)."
How do you propose we retain a standards pathway for infiltration?

**Comment by mdahlhausen** [comment]
Updates to make:
- [ ] Add PRM method to set infiltration rate values depending on 90.1 vintage
- [ ] Regenerate regression tests b/c of previous merges

**Comment by mdahlhausen** [comment]
@weilixu I updated the workflow, because the `casecmp` method wasn't correctly evaluating the field verification input field. The proposed uses 1.0 cfm/ft^2 unless field verification is present, in which case it uses 0.6. It doesn't use the existing infiltration rate.

Please take a look at the PRM test checks, and let me know if you think this needs any update.

**Comment by weilixu** [comment]
> @weilixu I updated the workflow, because the `casecmp` method wasn't correctly evaluating the field verification input field. The proposed uses 1.0 cfm/ft^2 unless field verification is present, in which case it uses 0.6. It doesn't use the existing infiltration rate.
> 
> Please take a look at the PRM test checks, and let me know if you think this needs any update.

Looks good to me. thank you Matt - I do not have comments on this updates.

**Review by weilixu — APPROVED** [review]

**Pull request merged**
